domain_path: /home/Yiann/Projects/DASD/test_vitis3/platform/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: /home/Yiann/FORGE/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
lang: c
